# Generated by Django 2.1.2 on 2018-10-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='places',
            field=models.ManyToManyField(to='real_events_app.Place'),
        ),
        migrations.AddField(
            model_name='member',
            name='professions',
            field=models.ManyToManyField(to='real_events_app.Profession'),
        ),
        migrations.AddField(
            model_name='member',
            name='teams',
            field=models.ManyToManyField(to='real_events_app.Team'),
        ),
        migrations.AddField(
            model_name='referee',
            name='meetings',
            field=models.ManyToManyField(to='real_events_app.Meeting'),
        ),
        migrations.AddField(
            model_name='team',
            name='meetings',
            field=models.ManyToManyField(to='real_events_app.Meeting'),
        ),
    ]
