# Generated by Django 2.1.2 on 2018-10-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_events_app', '0002_auto_20181022_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='info',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='info',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='member',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='info',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='place',
            name='info',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='referee',
            name='info',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='referee',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='info',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='staff',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='info',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
