# Generated by Django 2.1.2 on 2018-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_events_app', '0004_auto_20181022_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='post',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='member',
            name='post',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='newspost',
            name='post',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='place',
            name='post',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='referee',
            name='post',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='staff',
            name='post',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='team',
            name='post',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
